    <td width="185" height="600" valign="top" bgcolor="#FFCC99">
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
 <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="histoir.htm">Nos recherches au Cirad</a> </p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="sma.htm">Syst&egrave;mes multi-agents</a></p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="ecologi.htm">Approches &eacute;cologiques</a> </p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="gestion.htm">Deux approches de la</a><br><img src="/images/transparent.gif" width="26" height="12" align="top"><a href="gestion.htm">gestion des ressources</a> </p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="modelis.htm">Diff&eacute;rents</a><br><img src="/images/transparent.gif" width="26" height="12" align="top"><a href="modelis.htm">types de mod&egrave;les</a> </p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="usage.htm">Usage de la</a><br><img src="/images/transparent.gif" width="26" height="12" align="top"><a href="usage.htm">mod&eacute;lisation</a> </p>
      </td>
    <td width="25" height="600" valign="top" bgcolor="#FFFFFF">
    <img src="/images/coin_hg.gif" width="23" height="23">
</td>
