    <td width="185" height="600" valign="top" bgcolor="#FFCC99">
        <p>&nbsp;</p>
         <p>&nbsp;</p>
         <p>&nbsp;</p>
        
  <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="article.htm">Journal 
    articles</a> </p>
  <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="books">Books</a> 
  </p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="chapitre.htm">Book sections</a> </p>
        
  <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="communi.htm">Conference 
    proceedings</a> </p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="these.htm">PhD Theses</a> </p>
       
  <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="rapport.htm">Theses, 
    working papers</a> </p>
  <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="relatedPapers">External 
    papers</a></p>
  <p class="menu1" align="left">&nbsp; </p>

      </td>
    <td width="25" height="600" valign="top" bgcolor="#FFFFFF">
    <img src="/images/coin_hg.gif" width="23" height="23">
    </td>
