    <td width="185" height="600" valign="top" bgcolor="#FFCC99">
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="histoir.htm">Research within Cirad</a></p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="sma.htm">Multi-agent systems</a></p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="ecologi.htm">Ecological approaches</a></p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="gestion.htm">Two approaches for</a><br><img src="/images/transparent.gif" width="26" height="12" align="top"><a href="gestion.htm">managing resources</a> </p>
	  <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="modelis.htm">Different</a><br><img src="/images/transparent.gif" width="26" height="12" align="top"><a href="modelis.htm">types of models</a> </p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="usage.htm">Use of modelling</a></p>
      </td>
    <td width="25" height="600" valign="top" bgcolor="#FFFFFF">
    <img src="/images/coin_hg.gif" width="23" height="23">
</td>
