    <td width="185" height="600" valign="top" bgcolor="#FFCC99">
	<p><img src="/images/regle.gif" width="181" height="1"></p>

        <p>&nbsp;</p>

        <p>&nbsp;</p>

        <p>&nbsp;</p>

        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="../presentation">Cormas overview</a></p>

        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top">Download and install</p>

        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="../../classroom">Learn to use</a> </p>
		
		        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="../faq">Frequently Asked Questions</a> </p>

 	 
    </td>

    <td width="25" height="600" valign="top" bgcolor="#FFFFFF">

    <img src="/images/coin_hg.gif" width="23" height="23">

    </td>

