    <td width="185" height="600" valign="top" bgcolor="#FFCC99">
	<p><img src="/images/regle.gif" width="181" height="1"></p>

        <p>&nbsp;</p>

        <p>&nbsp;</p>

        <p>&nbsp;</p>

        <p>&nbsp;</p>

        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="../presentation">Vue d'ensemble</a> </p>

        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top">Téléchargement<br> et installation </p>

        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="/en/outil/classroom" target="_blank">Didacticiel</a> <img src="/images/English_Flag.gif" width="20" height="14" align="top"></p>
		
		        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="/en/outil/faq" target="_blank">Foire aux questions</a> <img src="/images/English_Flag.gif" width="20" height="14" align="top"></p>

 	 
    </td>

    <td width="25" height="600" valign="top" bgcolor="#FFFFFF">

    <img src="/images/coin_hg.gif" width="23" height="23">

    </td>

