    <td width="185" height="600" valign="top" bgcolor="#FFCC99">
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
       <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="formati.htm">Training courses</a> </p>
       <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="MISS-ABMS.htm">Upcoming training course</a> </p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="passe.htm">Past training sessions</a> </p>
      <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="asiaIT&C/asiaIT&CMain.htm">Past Asia IT&C project</a> </p>
   <p>&nbsp;</p>
        <p>&nbsp;</p> 
    <td width="25" height="600" valign="top" bgcolor="#FFFFFF">
    <img src="/images/coin_hg.gif" width="23" height="23">
    </td>
 