    <td width="185" height="600" valign="top" bgcolor="#FFCC99">

        <p>&nbsp;</p>

        <p>&nbsp;</p>

        <p>&nbsp;</p>

        <p>&nbsp;</p>

        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="http://www.commod.org/fr">ComMod</a></p>

        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="http://cormas.cirad.fr/fr/reseaux/form/forumCormas.php">Cormas forum</a></p>

        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="../equipe.htm">&Eacute;quipe de recherche</a></p>

        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="../liens.htm">S&eacute;lection de liens</a></p>

      </td>

    <td width="25" height="600" valign="top" bgcolor="#FFFFFF">

    <img src="/images/coin_hg.gif" width="23" height="23">

    </td>

