    <td width="185" height="600" valign="top" bgcolor="#FFCC99">
<p><img src="/images/regle.gif" width="181" height="1"></p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="ressource.htm">Gestion de ressources</a></p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="economie.htm">Fili&egrave;res et &eacute;changes</a></p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="espace.htm">Dynamiques</a><br><img src="/images/transparent.gif" width="26" height="12" align="top"><a href="espace.htm">d'occupation de l'espace</a></p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="jeuderole.htm">Jeux de r&ocirc;le</a></p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="theorique.htm">Mod&egrave;les th&eacute;oriques</a></p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="didactique.htm">Mod&egrave;les didactiques</a></p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="couplage.htm">Mod&egrave;les coupl&eacute;s</a></p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="tousmodeles.htm">Tous les mod&egrave;les</a></p>
     </td>
    <td width="25" height="600" valign="top" bgcolor="#FFFFFF">
    <img src="/images/coin_hg.gif" width="23" height="23">
    </td>

