    <td width="380" height="600" valign="top" bgcolor="#FFCC99">
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="index.html"><b>Tutorials</b></a></p>
        <p class="menu1" align="left">   <a href="example/GameofLife/">Game of Life(Conway)</a></p>        
        <p class="menu1" align="left">   <a href="example/FireModel/">FireAgent Model</a></p>
        <p class="menu1" align="left">   <a href="example/StupidModel/">StupidModel</a></p>	
		
     </td>

    <td width="25" height="600" valign="top" bgcolor="#FFFFFF">
    <img src="/images/coin_hg.gif" width="23" height="23">
    </td>

