    <td width="185" height="600" valign="top" bgcolor="#FFCC99">
        <p>&nbsp;</p>
         <p>&nbsp;</p>
         <p>&nbsp;</p>
        
  <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="article.htm">Articles</a> </p>
  <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="books">Livres</a> 
  </p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="chapitre.htm">Chapitres d'ouvrage</a> </p>
        
  <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="communi.htm">Actes de conf&eacute;rence 
   </a> </p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="these.htm">Th&egrave;ses de doctorat</a> </p>
       
  <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="rapport.htm">M&eacute;moires et rapports</a> </p>
  <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="poster.htm">Posters</a> </p>
  <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="relatedPapers.htm">Publications externes 
  </a></p>
  <p class="menu1" align="left">&nbsp; </p>

      </td>
    <td width="25" height="600" valign="top" bgcolor="#FFFFFF">
    <img src="/images/coin_hg.gif" width="23" height="23">
    </td>
