    <td width="240" height="600" valign="top" bgcolor="#FFCC99">
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p class="menu1" align="left"><img src="/images/puce.gif" width="26" height="12" align="top"><a href="../../../index.html"><b>Tutorials</b></a></p>
		
		<blockquote>
        <p class="menu1" align="left"> <a href="../../GameofLife/index.htm">Game of Life(Conway)</a></p>        
        <p class="menu1" align="left"> <a href="../../FireModel/index.htm">Fire Agent Model</a></p>
        <p class="menu1" align="left"> <a href="../../StupidModel/index.htm">StupidModel</a></p>
		
			<blockquote>
			<p class="menu1" align="left"> <a href="../../StupidModel/Smv1Cormas/index.htm">version <font face="WingDings 2" size=+1>u</font> </a></p>
			<p class="menu1" align="left"> <a href="../../StupidModel/Smv2Cormas/index.htm"><FONT FACE="WingDings" SIZE=+1></FONT>version <font face="WingDings 2" size=+1>v</font> </a></p>
			<p class="menu1" align="left"> <a href="../../StupidModel/Smv3Cormas/index.htm"><FONT FACE="WingDings" SIZE=+1></FONT>version <font face="WingDings 2" size=+1>w</font> </a></p>
			<p class="menu1" align="left"> <a href="../../StupidModel/Smv4Cormas/index.htm"><FONT FACE="WingDings" SIZE=+1></FONT>version <font face="WingDings 2" size=+1>x</font> </a></p>
			</blockquote>

		</blockquote>
     </td>
    <td width="25" height="600" valign="top" bgcolor="#FFFFFF">
    <img src="/images/coin_hg.gif" width="23" height="23">
    </td>

